theme: jekyll-theme-minimal
logo: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-qaOqfnHVFC7LoSG2V46XqqY5F_VfbuvX2tleSpLAKMiLjamp6lufpmTpiOMHGFREvv7ZdDx3iPg&usqp=CAU&ec=48665701
title: BIMM 143 Bioninformatics Lab Course
